### ISSUE TITLE
Allow BWA-MEM as an alternative mapper

### ISSUE THREAD

**Issue by marcelm** [FrickTobias/BLR#106]
I’ve benchmarked mapping 20 million reads against GRCh38 both with Bowtie2 and BWA-MEM.

These are the wall-clock runtimes (each mapper was run three times):

* BWA-MEM 0.7.17 (from Bioconda): 33m 30s, 33m 23s, 33m 31s
* Bowtie2 2.3.5 (from Bioconda): 43m 33s, 43m 22s, 43m 28s

CPU time was 492 minutes vs. 687 minutes.

I’d like to add BWA-MEM as an alternative mapper to the Snakefile. We can make it configurable, but given the numbers, BWA-MEM should probably be the default.

**Comment by pontushojer** [comment]
Yes BWA-mem is nice. I runned some small test with it and it also looked nice. I have previously also done some testing with the [Emerald](https://github.com/arshajii/ema) aligner. This is also uses on BWA-mem but is made for aligning barcoded short read such as 10x Genomics. It has some nice correction features that could be interesting to compare to both BWA and Bowtie2.
