### ISSUE TITLE
Consistency in argparse and comments

### ISSUE THREAD

**Issue by FrickTobias** [FrickTobias/BLR#110]
In line with what @marcelm pointed out in #109 we should also apply some of these comments in other scripts whenever applicable. The ones I have found we currently do not follow are:

**Argparser**
- help: `%(default)s` instead of hardcoded strings
- help: Write BAM rather than .bam
- Omit `type=str` in  (it is default)
- Use double dash `--` for multi-character option names (not only their long names)

**Comments**
- Write abbreviations without colon (e.g. ID:s => IDs)

**Comment by pontushojer** [comment]
This was fixed in #118
