### ISSUE TITLE
Test Emerald as alternative mapper 

### ISSUE THREAD

**Issue by pontushojer** [FrickTobias/BLR#114]
[Emerald github](https://github.com/arshajii/ema)

**Comment by pontushojer** [comment]
Emerald is only available through [conda for linux](https://anaconda.org/bioconda/ema). To use it on mac you need to use brew to install or install from source.

We could use brew as a workaround for now or update the [bioconda recipe ](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/ema/meta.yaml) to allow for osx.

**Comment by FrickTobias** [comment]
For the time being I'd make a workaround like we had with HapCUT2. 

I've briefly looked at the conda recipe, trying to compare it to the one for HapCUT2 which [Marcel made](https://github.com/bioconda/bioconda-recipes/pull/18553) but I must say I don't quite understand it as of now.

**Comment by marcelm** [comment]
i’m working on this now, see bioconda/bioconda-recipes#19002.

**Comment by marcelm** [comment]
You should now be able to `conda install ema` even on macOS.

**Comment by pontushojer** [comment]
Sweet! I have had so much trouble getting ema to install using brew on travis, this is much more convenient :)
