### ISSUE TITLE
Evaluate where more streaming can be used

### ISSUE THREAD

**Issue by marcelm** [FrickTobias/BLR#116]
More streaming can perhaps be employed. Currently, some large intermediate files are generated, some uncompressed, some compressed. This is slow: When writing them uncompressed, file I/O performance is likely a bottleneck. When writing them compressed, that takes a lot of CPU hours. Instead, one can let one program write uncompressed and send the output to the next program via a pipe. This avoids the intermediate file to disk entirely.

Perhaps this can be used for some of the intermediate BAM files. (And the other non-final ones should be marked as `temp()` as suggested in #115).

**Comment by pontushojer** [comment]
As noted in #133 we can pipe directly from the read trimming into the `tagfastq` script thereby skipping the intermediate `trimmed.1.fastq.gz` and `trimmed.2.fastq.gz` files.

**Comment by pontushojer** [comment]
I looked into the four steps `tagbam`, `clusterrmdup`, `buildmolecules` and `filterclusters` and this in our current possibilities for streaming: 
- **`tagbam`: Streaming possible**
- `clusterrmdup`: No streaming
- `buildmolecules`: No streaming
- **`filterclusters`: Streaming possible**

`clusterrmdup` and `buildmolecules` read in the file two times and thus require the input to be read from disc.
