### ISSUE TITLE
example doesn't complete 

### ISSUE THREAD

**Issue by colsen** [FrickTobias/BLR#12]
Hello, 

when I run
bash ../BLR_automation.sh -r  testdata_read1.fastq.gz testdata_read2.fastq.gz testdata_analysis

the script runs only runs until step 3 and doesn't complete. Do you have any idea why this is?
bowtie2 version: 2.3.4.3

Thanks for your help.

Below: command line output and content of 3_map.log 

0. Argparsing & options
Read 1:	testdata_read1.fastq.gz
Read 2:	testdata_read2.fastq.gz
Output:	testdata_analysis

Threads:	1
Starts at step:	1
End after step:	4

Wed Feb 27 16:46:07 CET 2019	ANALYSIS STARTING

1. Demultiplexing
Wed Feb 27 16:46:07 CET 2019	1st adaptor removal
Wed Feb 27 16:46:08 CET 2019	1st adaptor removal done
Wed Feb 27 16:46:08 CET 2019	Barcode extraction
Wed Feb 27 16:46:08 CET 2019	Barcode extraction done
Wed Feb 27 16:46:08 CET 2019	2nd adaptor removal
Wed Feb 27 16:46:09 CET 2019	2nd adaptor removal done
Wed Feb 27 16:46:09 CET 2019	3' trimming
Wed Feb 27 16:46:09 CET 2019	3' trimming done
Wed Feb 27 16:46:09 CET 2019	Intact reads: 0.973162 %

2. Clustering
Wed Feb 27 16:46:09 CET 2019	Barcode fasta generation
Wed Feb 27 16:46:09 CET 2019	Barcode fasta generation done
Wed Feb 27 16:46:09 CET 2019	Barcode clustering
Wed Feb 27 16:46:10 CET 2019	Barcode clustering done

3. Mapping
Wed Feb 27 16:46:10 CET 2019	Mapping

The content of 3_map.log file:
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[main_samview] fail to read the header from "-".

**Comment by FrickTobias** [comment]
Hi, thank you for bringing this issue to my attention.

As you seem to be suspecting, the mapping command does not seem to work properly. I'll try and reproduce the issue first; and your mentioned Bowtie2 2.4.3.4 but what version of samtools are you running? The output from Bowtie2 is being piped into samtools directly and it is that error message you're seeing being logged in the 3_map.log file.

**Comment by colsen** [comment]
Updating to the last samtools version worked. Thanks for your help!

**Comment by FrickTobias** [comment]
No problem!
