### ISSUE TITLE
Simplify how binaries are found

### ISSUE THREAD

**Issue by marcelm** [FrickTobias/BLR#122]
The pipeline currently requires that the paths to Picard and HapCUT2 are set in the configuration file. This should not be necessary. Instead, we should simply expect that the programs are installed and available on the $PATH. Since we recommend users to install BLR with Conda, this will work.

This affects the `picard_command` and `hapcut2` configuration settings. For HapCUT2, we may need a Conda recipe first (#90).

**Comment by FrickTobias** [comment]
Finished
- [x] picard
- [ ] HapCUT2
