### ISSUE TITLE
Phase all reads into phase blocks

### ISSUE THREAD

**Issue by FrickTobias** [FrickTobias/BLR#130]
Currently only reads at heterozygous sites are being phased and numerous LSV callers require reads to be tagged with HP tags (haplotype tags). So in order to test and evaluate LSV callers we are required to phase all reads.

This should be done by phasing the molecules according to the hetSNV sites they cover.

**Comment by pontushojer** [comment]
This was fixed in https://github.com/NBISweden/BLR/pull/4.
