### ISSUE TITLE
Introduce LSV calling to pipeline

### ISSUE THREAD

**Issue by FrickTobias** [FrickTobias/BLR#131]

**Comment by FrickTobias** [comment]
Currently investigating the following software:
- [LinkedSV](https://github.com/WGLab/LinkedSV)
- [GROCSVS](https://github.com/grocsvs/grocsvs)
- [NAIBR](https://github.com/raphael-group/NAIBR)
- Custom variant calling used in [CPTv2](https://www.ncbi.nlm.nih.gov/pubmed/28650462)

**Comment by pontushojer** [comment]
I found a new tools that we can test:
- [SvABA](https://github.com/walaj/svaba) (from published [article](https://genome.cshlp.org/content/28/4/581.full))

**Comment by FrickTobias** [comment]
I think this is a different issue to address as SvABA looks at short deletions (they mention being efficient at sizes 20-300 bp and also calling variants <1000 bp). As I understand it, this is usually detected and analyzed in discrete steps, one for shorter and one for longer SVs (sizes ~kbp).

**Comment by pontushojer** [comment]
So as I understand is this tool is different in that it can detect both short and longer structural variants. But it also seems that their definition of large is not as large as these other tools, they mention >300 bp as large in their tables.

**Comment by pontushojer** [comment]
I also found this tools called [ZoomX](https://bitbucket.org/charade/zoomx) ([article](https://academic-oup-com.focus.lib.kth.se/nar/article/46/4/e19/4658832) where they compare against LongRanger) that might me worth testing.

**Comment by FrickTobias** [comment]
> So as I understand is this tool is different in that it can detect both short and longer structural variants. But it also seems that their definition of large is not as large as these other tools, they mention >300 bp as large in their tables.

I think the nomenclature here is a bit fussy, since large and small doesn't really say much. However if you were to compare it to the Longranger output, those SVs would end up in the same files as  their short variations.

I'm trying to use the nomenclature roughly like 
SNVs - single bases
indels / small SVs - more than 1 bp, up to ~1kb
LSVs - over 1 kb

> I also found this tools called [ZoomX](https://bitbucket.org/charade/zoomx) ([article](https://academic-oup-com.focus.lib.kth.se/nar/article/46/4/e19/4658832) where they compare against LongRanger) that might me worth testing.

Definitely worth looking into! Although since they don't compare to any other LSV calling algorithm I think it might not be as good, but I'll look into it!

**Comment by pontushojer** [comment]
New possible tool to integrate. [VALOR2](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-01975-8)

**Comment by pontushojer** [comment]
New tool, [Novel-X](https://github.com/1dayac/Novel-X#publications) specific for insertions.

>Novel-X detects and genotypes novel sequence insertions in 10X sequencing dataset using non-trivial read alignment signatures and barocde information.

Preprint: https://www.biorxiv.org/content/10.1101/551028v1.full

**Comment by pontushojer** [comment]
New SV caller specifically made for stLFR type reads, [stLFRsv](https://github.com/BGI-biotools/stLFRsv)

Preprint: https://www.biorxiv.org/content/10.1101/2020.06.15.141721v1.full.pdf

**Comment by pontushojer** [comment]
New tool: https://github.com/morispi/LEVIATHAN
Article: https://doi.org/10.1101/2021.03.25.437002
