### ISSUE TITLE
buildmolecules not outputting stats_file 

### ISSUE THREAD

**Issue by pontushojer** [FrickTobias/BLR#144]
The `buildmolecules`script has a `-s`/`--stats-file` option to output barcode/molecule statistics files. This is currently not default in the snakemake pipeline, but it should be.

**Comment by FrickTobias** [comment]
Hm, I'd like to remember that we removed it in favor of always outputting the stats but I'll look into it.

**Comment by FrickTobias** [comment]
I think this if left since it was part of `filterclusters` but I don't see why we shouldn't implement it. It will take some time to write the file but that should be negligible.
