### ISSUE TITLE
Non-diploid calls

### ISSUE THREAD

**Issue by FrickTobias** [FrickTobias/BLR#146]
From running the current pipeline without a reference `vcf` file I am getting non-diploid calls. These are then causing problems for HapCUT2 when trying to phase them.

However according to the `freebayes` documentation it seems like we should only get diploid samples.

["Call variants assuming a diploid sample"](https://github.com/ekg/freebayes)
```
freebayes -f ref.fa aln.bam >var.vcf
```

Current command used in Snakefile for variant calling

```
"freebayes"
" -f {config[reference]}.fasta"
" {input.bam} 1> {output.vcf} 2> {log}"
```

**Comment by FrickTobias** [comment]
I'm currently trying to run it using `-p 2` to see if it only the default which is not working properly.

**Comment by marcelm** [comment]
How do these calls look in the VCF?

**Comment by pontushojer** [comment]
This is from the error message:

```
ERROR: Non-diploid VCF entry detected. Each VCF entry must have a diploid genotype (GT) field consisting of two alleles in the set {0,1,2} separated by either '/' or '|'. For example, "1/1", "0/1", and "0|2" are valid diploid genotypes for HapCUT2, but "1", "0/3", and "0/0/1" are not.
The invalid entry is: 

chr1	28588	.	GTTTTTTTTTTTTTTTGCATC	GTTTGGTTTTTTTTTTTTTTTTGCATC,GTTTGGTTTTTTTTTTTTTGCATC,GTTTGGTTTTTTTTTTTTGCATC	2.28394	.	AB=0,0,0;ABP=0,0,0;AC=0,0,2;AF=0,0,1;AN=2;AO=2,2,3;CIGAR=1M6I20M,3M3I18M,4M2I17M;DP=9;DPB=10.8571;DPRA=0,0,0;EPP=3.0103,3.0103,3.73412;EPPR=0;GTI=0;LEN=6,3,2;MEANALT=5,5,5;MQM=4,6,4.66667;MQMR=0;NS=1;NUMALT=3;ODDS=1.28421;PAIRED=1,1,1;PAIREDR=0;PAO=1,0,0;PQA=37,0,0;PQR=0;PRO=0;QA=8,12,14;QR=0;RO=0;RPL=1,1,1;RPP=3.0103,3.0103,3.73412;RPPR=0;RPR=1,1,2;RUN=1,1,1;SAF=0,2,2;SAP=7.35324,7.35324,3.73412;SAR=2,0,1;SRF=0;SRP=0;SRR=0;TYPE=ins,ins,ins	GT:DP:AD:RO:QR:AO:QA:GL	3/3:9:0,2,2,3:0:0:2,2,3:8,12,14:-0.701801,-0.925445,-0.323385,-0.657468,-0.880116,-0.0554079,-0.90309,-1.12633,-0.856154,0
````

**Comment by marcelm** [comment]
There are three ALT alleles and the genotype is 3/3. So the call that FreeBayes made here is a bit weird, but in the end, it’s a homozygous insertion and could just be left unphased. Some options:
- Add an extra step to filter/fix these types of variants
- Ask the HapCUT2 authors to change their program such that it accepts these variants
- Somehow get FreeBayes to not output these variants

**Comment by FrickTobias** [comment]
From speaking with the author to, `freebayes` it seems it will always output those variants. They said using `vcffilter` like the following would solve the problem.
```
vcffilter "AC > 0" var.vcf > var-filt.vcf
```
However, I havn't checked what the command actually does so I'll get back on this when I've read/tested it a bit.

**Comment by FrickTobias** [comment]
The `vcffilter` command removes all genotypes which have less than 1 allele counts (see [VCF 4.2](https://samtools.github.io/hts-specs/VCFv4.2.pdf) docs) and it solves the problem.
