### ISSUE TITLE
Organize files in analysis folder 

### ISSUE THREAD

**Issue by pontushojer** [FrickTobias/BLR#155]
The current structure is completely flat and need some organization to make it easier to overview. My suggestion would be to follow something similar to [this proposed project structure](https://github.com/NBISweden/project_template) as far as it applies.

**Comment by FrickTobias** [comment]
I agree that would be good, however I also think that project folder structure overcomplicates a lot of things for out purposes. I'd go for something more like input, output + supporting stuff (in this case logs, tmp and some intermediate files we currently are not deleting).

```
|- input-files/
|  |- fastq-files/            input fq links
|  |- configs/            pipe settings files
|
|- intermediate-files/            Non-necessary files (represented in final results as well)
|  |- final-trimmed/
|  |- barcodes/
|
|- results/            
|  |- output-files/            final BAM and vcf file
|  |- reports/            overview report & plots used to create said report
|
|- tmp/            temporary files
|- logs/            log files & dag
```

That said I also think one of our biggest problem with the flat style we have now is that we are duplicating out BAM files for every step. If we instead write them as tmp files and only create a log directory we go from having an output folder looking like this:

```
bamtofq.log
barcode-merges.csv
barcodes.clstr
barcodes.fasta
blr.yaml
buildmolecules.log
clusterrmdup.log
cutadapt_extract_DBS.log
cutadapt_trim.log
filterclusters.log
hapcut2_extracthairs.log
hapcut2_linkfragments.log
hapcut2_phasing.log
mapped.sorted.bam
mapped.sorted.tag.bam
mapped.sorted.tag.mkdup.bam
mapped.sorted.tag.mkdup.bam.bai
mapped.sorted.tag.mkdup.bcmerge.bam
mapped.sorted.tag.mkdup.bcmerge.mol.bam
mapped.sorted.tag.mkdup.bcmerge.mol.filt.bam
mapped.sorted.tag.mkdup.bcmerge.mol.filt.bam.bai
mapped.sorted.tag.mkdup.bcmerge.mol.filt.linked.txt
mapped.sorted.tag.mkdup.bcmerge.mol.filt.phase
mapped.sorted.tag.mkdup.bcmerge.mol.filt.phase.phased.VCF
mapped.sorted.tag.mkdup.bcmerge.mol.filt.unlinked.txt
mark_duplicates.log
phasing_stats.txt
read_mapping.log
reads.1.fastq.gz
reads.1.final.fastq.gz
reads.2.fastq.gz
reads.2.final.fastq.gz
reference.vcf
starcode_clustering.log
tag_bam.stderr
tag_fastq.log
trimmed.barcoded.1.fastq.gz
trimmed.barcoded.2.fastq.gz
```

To one looking like this:

```
logs/
barcodes.clstr
barcodes.fasta
blr.yaml
mapped.sorted.tag.mkdup.bcmerge.mol.filt.bam
mapped.sorted.tag.mkdup.bcmerge.mol.filt.phase.phased.VCF
mapped.sorted.tag.mkdup.bcmerge.mol.filt.unlinked.txt
reads.1.fastq.gz
reads.1.final.fastq.gz
reads.2.fastq.gz
reads.2.final.fastq.gz
reference.vcf
trimmed.barcoded.1.fastq.gz
trimmed.barcoded.2.fastq.gz
```

**Comment by marcelm** [comment]
I’m a fan of flat hierarchies. Not having to `cd` into too many directories is a plus in my opinion. That said, a little bit of structure wouldn’t hurt. I would take this one step at a time. A good first additional directory could be `results/`. But I would actually not add subdirectories under it. When it becomes too messy, they can still be added.

Also, marking files as temporary is another good clean-up measure as Tobias said.

A thought about logs: I understand the desire to have them in a separate `logs/` folder, but in some projects, I have found it convenient to instead keep them alongside the actual output file whose creation they describe. For example, one could keep the BWA log in `mapped.sorted.bam.log`, the duplicate marking log in `mapped.sorted.tag.mkdup.bam.log` etc. Some cases are a bit ambiguous (if a single process creates multiple output files, for example), but if you want to see how a file was generated (for debugging or just statistics), this makes it very easy to find the associated log file.
