### ISSUE TITLE
HapCUT2 linkfragments bug

### ISSUE THREAD

**Issue by FrickTobias** [FrickTobias/BLR#159]
Found a [bug](https://github.com/vibansal/HapCUT2/issues/77) in HapCUT2 when working on full size files datasets. I will leave this open until it is resolved from their end since we're dependent on it to phase our linked reads.

**Comment by FrickTobias** [comment]
Update: The bug is patched in the [possible_tenx_utf8_fix branch](https://github.com/vibansal/HapCUT2/tree/possible_tenx_utf8_fix).

**Comment by pontushojer** [comment]
This should be fixed with the newest version of hapcut2 being released.
