### ISSUE TITLE
EMA: investigate how sorting scales with big data

### ISSUE THREAD

**Issue by FrickTobias** [FrickTobias/BLR#169]
Files have to be sorted on barcode before mapped with EMA. This is currently not tested for big files, see discussion in #168.

**Comment by pontushojer** [comment]
**Test run on 476,994,630 read pairs.**
Cores: 1
Command: 
```
pigz -cd -p 1 trimmed.barcoded.2.fastq.gz | paste - - - - | sort -t '_' -k3  | tr '\t' '\n' | pigz > /dev/null
```

**`time` output:**
- real	363m32.519s 
- user	881m53.867s
- sys	37m16.807s

**jobstats**
![image](https://user-images.githubusercontent.com/27061883/70225364-2e9b3400-174f-11ea-8715-14bacaca7c3d.png)
