### ISSUE TITLE
EMA: mapping corner cases

### ISSUE THREAD

**Issue by FrickTobias** [FrickTobias/BLR#170]
Some reads are being removed when mapped with EMA (those without barcode and those with N-base containing ones). They are very few, but they could be mapped separately with `bwa` and added to file, see discussion in #168.

**Comment by pontushojer** [comment]
Fixed in https://github.com/NBISweden/BLR/commit/3f3e3240f42bb3d6d0e7ff666825ca48fe8ad7ed
