### ISSUE TITLE
Add Lariat

### ISSUE THREAD

**Issue by FrickTobias** [FrickTobias/BLR#172]
[Lariat](https://github.com/10XGenomics/lariat) is a mapper short linked reads used by Longranger and such is probably the most frequently used. Consequently we should investigate its performance.

**Comment by pontushojer** [comment]
**Things to note about Lariat:**
1) Uses special[ input format](https://github.com/10XGenomics/lariat#input-file-format).

> The SORT_FASTQS stage in Long Ranger creates specially formatted, barcode sorted input for lariat. We recommend using those input files to experiment with changes to lariat. Lariat requires input data in a non-standard FASTQ-like format. Each read-pair is formatted as a record of 9 consecutive lines containing:
> 
> read header
> read1 sequence
> read1 quals
> read2 sequence
> read2 quals
> 10X barcode string
> 10X barcode quals
> sample index sequence
> sample index quals
> Read pairs must be sorted by the 10X barcode string. The 10X barcode string is of the form 'ACGTACGTACGTAC-1'.

2) Is not available for conda install. Also it has no formal software release i.e. we cannot make a conda recipe. Thus is has to be built from source.

**Comment by FrickTobias** [comment]
Or we could to create a release ourselves.

**Comment by pontushojer** [comment]
Testing in branch https://github.com/NBISweden/BLR/tree/integrate-lariat
