### ISSUE TITLE
Subset script

### ISSUE THREAD

**Issue by FrickTobias** [FrickTobias/BLR#183]
I've numerous times found myself needing a subset of reads where barcode integrity also can be investigated, but this is a but tedious to create if you want:
 - All reads at a certain location 
 - All reads belonging to the molecules found at that location

So it could be nice to have some kind of toolbox script for extracting a subset with these properties.

**Comment by pontushojer** [comment]
> - All reads at a certain location

I have done this using samtools view by specifying a range e.g. `samtools view -bh input.bam chr1:100212001-100223251 > range.bam`. What did you have in mind here?

**Comment by pontushojer** [comment]
> - All reads belonging to the molecules found at that location

Do you mean specifying a location add only extracting reads assigned to a molecule at that location? Or extracting the full lengths (with all connected reads) of the molecules overlapping the specified location?
