### ISSUE TITLE
Make test data creation reproducible

### ISSUE THREAD

**Issue by marcelm** [FrickTobias/BLR#207]
For parallelization by chromosome (#205), we need a new test dataset that contains at least two "chromosomes". Creating a new one from scratch has become difficult as the documentation (a text file on the cluster file system) is incomplete and in particular because the steps need to be done manually.

We should add a proper `Snakefile` whose only purpose is to create the test dataset.

**Comment by pontushojer** [comment]
Files that need to be included in Snakefile (currently in `blr-testdata-0.4.2`):

- [ ]  blr_reads.1.fastq.gz
- [ ]  blr_reads.2.fastq.gz
- [ ]  ref.fasta
- [ ]  dbSNP.chr1mini.vcf.gz
- [ ]  dbSNP.chr1mini.vcf.gz.tbi
- [ ]  HG002_GRCh38_GIAB_highconf.chr1mini.vcf
- [ ]  HG002_GRCh38_GIAB_highconf_triophased.chr1mini.vcf
- [ ]  stlfr_barcodes.txt
- [ ]  stlfr_reads.1.fastq.gz
- [ ]  stlfr_reads.2.fastq.gz
- [ ]  tellseq_index.fastq.gz
- [ ]  tellseq_reads.1.fastq.gz
- [ ]  tellseq_reads.2.fastq.gz
- [ ]  tenx_barcode_whitelist.txt
- [ ]  tenx_reads.1.fastq.gz
- [ ]  tenx_reads.2.fastq.gz

I am currently working on fixing the FASTQs and barcode files.
