### ISSUE TITLE
Chunk specific runtime artefacts in clusterrmdup

### ISSUE THREAD

**Issue by pontushojer** [FrickTobias/BLR#229]
The runtime for the `clusterrmdup` (`find_clusterdups` after PR https://github.com/NBISweden/BLR/pull/30 merges) step is  much longer for chrY than other chromosomes. See the following graphs below generated based on data in `/proj/uppstore2018173/private/pontus/runs/200819._synchronise-merges_rerun`. I have also seen this phenomenon in other runs.  

<img width="600" alt="Screenshot 2020-09-01 at 14 39 12" src="https://user-images.githubusercontent.com/27061883/91852300-e9198200-ec60-11ea-9f5d-f161a87d0b72.png">

**Runtime vs mean coverage for each chromosome.  For chrM this is the sum of all small contigs that make up this "chunk".**

<img width="600" alt="Screenshot 2020-09-01 at 14 39 30" src="https://user-images.githubusercontent.com/27061883/91852321-f3d41700-ec60-11ea-8f94-05daee790da1.png">

**Runtime vs total contig length for each chromosome. For chrM this is the sum of all small contigs that make up this "chunk".**

From these figures it is clear that chrY for some reason take longer that should be predicted based on coverage and contig length. Chr16 also somewhat breaks this pattern. 

What could be the reason for this??

**Comment by marcelm** [comment]
chr1 also doesn’t follow the pattern. Or is this an artifact?

**Comment by pontushojer** [comment]
Yeah its true chr1 also takes longer than expected. It was however not as striking as chrY but still this might relate to a shared issue.

**Comment by pontushojer** [comment]
I did a check for a separate dataset and compared against all other rules that are run for the chunks. Looking at this we see that chr1, chr16, chr21 (somewhat less though) and chrY stick out from the rest (see the red trace for clusterrmdup).

<img width="948" alt="Screenshot 2020-09-03 at 17 50 42" src="https://user-images.githubusercontent.com/27061883/92137871-0049a280-ee0e-11ea-97e1-3bc14715ac29.png">
