### ISSUE TITLE
How to use wfa2tenx or BLR_metagenomics?

### ISSUE THREAD

**Issue by YichaoOU** [FrickTobias/BLR#237]
Hello,

I have generated `reads.1.final.fastq.gz`, `reads.2.final.fastq.gz`, and `barcodes.clstr` (our own data). I want to get the final assembled fasta file.

If I run `BLR_metagenomics`, I had:

```
Traceback (most recent call last):
  File "./python_scripts/tag_fastq.py", line 157, in <module>
    if __name__=="__main__": main()
  File "./python_scripts/tag_fastq.py", line 26, in main
    name,bc_seq = record.id.split('_')
```

If I run `wfa2tenx`, I had:

```
python wfa2tenx.py -1 reads.1.final.fastq -2 reads.2.final.fastq

Found:	0 WFA barcodes
Made:	0 10X barcodes

```

Any suggestions?

Thanks,
Yichao

**Comment by FrickTobias** [comment]
### BLR metagenomics

For `BLR_metagenomics`, what command did you use?

### wfa2tenx

For `wfa2tenx` it seems like wfa2tenx cannot identify the barcode sequences in the header of the read sequences. 

A solution would be to manually modify the header of the reads in `reads.*.final.fastq.gz` so it matches the pattern which `wfa2tenx` looks for, which I believe by default is a 20 character string with only ATCG. If you use `--v1` it should look for `RG:Z:*`.

I'm not sure exactly what format your output has, but you can check that by running `head reads.1.final.fastq`. And if there is something else in the barcode header (e.g. `BC:Z:*`) I would exchange it using bash. Something along the lines of this should work:

```
for i in reads.*.final.fastq; do cat $i | paste - - - - | tr "BC:Z:" "RG:Z:" > $i.RG-header.fastq; done
```

**Comment by FrickTobias** [comment]
I'm closing this issue for now. If the problem persists or if you can provide additional information feel free to reopen this issue.
