### ISSUE TITLE
Make barcode merging configurable

### ISSUE THREAD

**Issue by pontushojer** [FrickTobias/BLR#241]
Currently only two duplicate read pairs within the defined window are required to merge two barcodes. Making it configurable to any minimum number of reads would be good.

**Comment by FrickTobias** [comment]
I think this was looked into back around 2017 and it showed that increasing the number of proximal duplicate read pairs only decreased sensitivity, so I would first do a quick check to see if this is needed or just feature creep!

**Comment by pontushojer** [comment]
> nk this was looked into back around 2017 and it showed that increasing the number of proximal duplicate read pairs only decreased sensitivity, so I would first do a quick check to see if this is needed or just feature creep!

I guess you tested on BLR reads? My thinking here is that technologies such as 10x that have a lot of reads per fragment might generate faulty barcode merges at a higher rate. Thus it would be good to control this somehow. None the less we should check that this is actually beneficial before integrating.

**Comment by FrickTobias** [comment]
Indeed it was BLR reads. 

However, we did a rough estimation of the risk for random barcode collision. Which ended up being something like the combination of this:

- Same **5' pos** for **r1** in a **primary duplicate** (per read: 1 in 3*10^9 * `num_reads`)
- Same **5' pos** for **r2** in that **primary duplicate** (per read: 1 in `ave_read_len`)
- Same **5' pos** for **r1** in a **secondary duplicate** (per read: `ave_reads_per_mol` in `ave_mol_len`)
- Same **5' pos** for **r2** in that **secondary duplicate** (per read: 1 in `ave_read_len`)

**Total risk:**

`num_reads` / (`genome_size` * `read_len` / `reads_per_mol` * `ave_mol_len` * `read_len`)

**Variables:**

`num_reads` = 100,000,000
`genome_size` = 3*10^9
`read_len` = 150
`reads_per_mol` = 100
`ave_mol_len` = 10000

**Risk of barcode collision:**

`100,000,000` / (`3 * 10^9` * `150` / `100` * `10000` * `150`) ~= 1.5*10^-8
