### ISSUE TITLE
Rethink phaseblock length plot in report

### ISSUE THREAD

**Issue by pontushojer** [FrickTobias/BLR#243]
The plot currently looks at this for most libraries.

![phasingblock_lengths (2)](https://user-images.githubusercontent.com/27061883/132696404-82cecadd-ef02-4511-af8c-a1d206eae8d3.png)

This is not very useful and its hard to compare phaseblocks length between libraries. 

Ideas:
- [Nx plot](https://lh3.github.io/2020/04/08/a-new-metric-on-assembly-contiguity)

**Comment by pontushojer** [comment]
I added the Nx plot in https://github.com/NBISweden/BLR/commit/a9d029ed626ebaf1993ad7045370b2da11896b40 since this seems like good addition that could be generated from the same data as the plot above. It is visable more useful, see example below using same data as above.

![phasingblock_nx](https://user-images.githubusercontent.com/27061883/132723573-86541dbd-7570-445e-a1fb-6844e6edf584.png)

I left the old plot in as it replicates a plot that is part of the LongRanger summary report which some might find useful. Possibly I might revaluate this.

**Comment by FrickTobias** [comment]
It looks to me like the first plot just needs some binning, or? And what's x in the Nx plot? Hard for the user to interpret I'm thinking.

**Comment by pontushojer** [comment]
> It looks to me like the first plot just needs some binning, or? And what's x in the Nx plot? Hard for the user to interpret I'm thinking.

I guess we could changed how things are binned for the first plot, question is how to do so in a way that still makes this useful. I will think a bit on this..

I included this description above the Nx plot, hopefully this clarifies things:

"Phaseblock contiguity as Nx curve. Each point y corresponds to the length of the phaseblock for which the collection of all phaseblocks of that length or longer contains at least x% of the sum of the lengths of all phaseblocks."
