### ISSUE TITLE
Add new option to filterclusters script to include Tn5 related overlaps.

### ISSUE THREAD

**Issue by pontushojer** [FrickTobias/BLR#50]
Related to [comment](https://github.com/FrickTobias/BLR/commit/b9119f19c13b126cc28c67d1c01a406f9fc5de69#r34116604)

This is ment as a future improvement and is no current issue. Just writing it here to remember.

**Comment by FrickTobias** [comment]
FYI: This is being investigated (and is almost done by @Parharn).
