### ISSUE TITLE
MD5 sum comparisons should be removed as they are hard to diagnose

### ISSUE THREAD

**Issue by marcelm** [FrickTobias/BLR#99]
I’ve noticed some test failures because the MD5 sums of a BAM file didn’t match. These problems are hard to diagnose since it is not clear exactly what the difference is. Also, it appears to me as if the MD5 sometimes changes even if nothing was done that should influence it.

**Comment by FrickTobias** [comment]
I think has been solved by the implementation of pytest #126 which for most cases provides more specific information of what fails.

**Comment by marcelm** [comment]
#126 was a step towards solving this problem, but the MD5 sum comparisons are still in the test script, so it would be justified to leave this issue open until those are actually gone. But I get rid of them as one of my next tasks so we won’t forget.

**Comment by FrickTobias** [comment]
I closed the issue since it (as I understood it) specified it is hard to diagnose rather than that it should be removed. So I agree we should move away from it, I just saw the issue patched as it was written in the title/description.

I'll reopen the issue to make sure it's not forgotten.
